# config/_default/languages.en.toml

title = "gbrls"

[author]
#name = "Gabriel Schneider"
#image = "img/author.jpg"
#headline = "A generally awesome human"
#bio = "A little bit about me"
#links = [
#  { twitter = "https://twitter.com/username" }
#]
