colorScheme = "blowfish"

defaultBackgroundImage = "pattern.svg"
#defaultBackgroundImage = "pattern.svg"
#defaultFeaturedImage = "eoe.png"
highlightCurrentMenuArea = true
enableCodeCopy = true

footer.showCopyright = false
footer.showThemeAttribution = false

header.layout = "basic"

[homepage]
layout = "background"
showRecent = true
cardView = false
layoutBackgroundBlur = true
showRecentItems = 32


[article]
showAuthor = false
showWordCount = false
showTableOfContents = true
heroStyle = "background"
showHero = true
layoutBackgroundBlur = true
showAuthorsBadges = true



