baseURL = "https://gbrls.github.io"
languageCode = "en-us"
title = "Gabriel Schneider's homepage"
theme = "gbrls"

googleAnalytics = "UA-116679276-1" 

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "abap"
    tabWidth = 4
