[kodama]
trees = "trees"
assets = "assets"
base-url = "/"
themes = ["themes/moon_gbrls.html"]

[toc]
placement = "right"
sticky = true
mobile-sticky = true
max-width = "45ex"

[text]
edit = "[edit]"
toc = "Table of Contents"
references = "References"
backlinks = "Backlinks"

[build]
typst-root = "trees"
short-slug = false
pretty-urls = false
footer-mode = "link"
inline-css = false
inline-script = false
asref = false
output = "./publish"

[serve]
edit = "vscode://file/"
output = "./.cache/publish"
command = ["miniserve", "<output>", "--index", "index.html", "--pretty-urls"]
