name: Build website with Zola

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zola Deploy to Pages
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: gbrls/action-dropbox-download@v1.0.1
        with:
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: '/journal'
          destination-path: '/tmp/from-dropbox'
          
      - name: 'Filter files to publish'
        run: |
          pip install -r scripts/requirements.txt
          ./scripts/filter.py /tmp/from-dropbox ./content
      
        
