name: Full website build (Dropbox, Zola)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gbrls/action-dropbox-download@v1.0.2
        with:
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: '/journal'
          destination-path: 'from-dropbox'   
      - name: 'Filter files to publish'
        run: |
          ls
          sudo chmod -R 666 from-dropbox
          sudo find from-dropbox
          pip install -r scripts/requirements.txt
          sudo ./scripts/filter.py from-dropbox ./content > p-output.txt
          sudo cat p-output.txt
          find content
      - name: Zola Deploy to Pages
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
